import { VehicalService } from 'src/app/helper/services/vehicals/vehical.service';
import { Component, ElementRef, OnInit, Renderer2 } from '@angular/core';
import { UntypedFormControl, UntypedFormGroup, ValidatorFn, Validators } from '@angular/forms';
import { DialogRef, DialogService } from '@progress/kendo-angular-dialog';
import { NotificationService } from '@progress/kendo-angular-notification';
import { DropdownItem } from 'src/app/helper/models/common/dropdown/dropdown-item.model';
import { VehicalModel } from 'src/app/helper/models/vehicals/vehical-model';
import { CommonService } from 'src/app/helper/services/common/common.service';
import { UtilityService } from 'src/app/helper/services/common/utility.service';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { AlertService } from 'src/app/helper/services/common/alert.service';
import { VehicalTypeService } from 'src/app/helper/services/vehicals/vehical-type.service';
import { UtilityRix } from 'src/app/helper/common/utility-rix';
import { ResponseModel } from 'src/app/helper/models/common/response-model';

@Component({
  selector: 'app-vehical-edit',
  templateUrl: './vehical-edit.component.html',
  styleUrls: ['./vehical-edit.component.css']
})
export class VehicalEditComponent implements OnInit {

  id: string;
  editMode = false;
  model: VehicalModel;
  form: UntypedFormGroup;

  typeList: DropdownItem<string>[];

  constructor(
    private renderer: Renderer2,
    private el: ElementRef,
    private notificationService: NotificationService,
    private dialogService: DialogService,
    public utilityService: UtilityService,
    private commonService: CommonService,
    private vehicalService: VehicalService,
    private vehicalTypeService: VehicalTypeService,
    private router: Router,
    private route: ActivatedRoute,
    private alertService: AlertService
  ) { }

  ngOnInit(): void {

    this.route.params
      .subscribe((params: Params) => {
        if (params.id != null) {
          this.id = params.id;
          this.vehicalService.get(params.id)
            .subscribe((model: VehicalModel) => {
              this.model = model;
              this.editMode = true;
              this.initForm();
            });
        } else {
          this.initForm();
        }
      });

    this.vehicalTypeService.getDropdownList('')
      .subscribe((list: DropdownItem<string>[]) => {
        this.typeList = list;
      });

  }

  private initForm(): void {

    let vehicalIdStr: string = '<auto-generated>';
    let registrationPlate: string = null;
    let active: boolean = false;
    let make: string = null;
    let model: string = '';
    let modelYear: number = null;
    let type: DropdownItem<string> = null;
    let color: string = null;
    let armoured: boolean = false;

    if (this.model) {
      vehicalIdStr = this.model.vehicalIdStr;
      registrationPlate = this.model.registrationPlate;
      active = this.model.active;
      make = this.model.make;
      model = this.model.model;
      modelYear = this.model.modelYear;
      type = this.model.type;

      color = this.model.color;
      armoured = this.model.armoured;
    }

    this.form = new UntypedFormGroup({
      vehicalIdStr: new UntypedFormControl(
        vehicalIdStr, [Validators.required]),
      registrationPlate: new UntypedFormControl(
        registrationPlate, [Validators.required]),
      active: new UntypedFormControl(
        active, [Validators.required]),
      make: new UntypedFormControl(
        make, [Validators.required]),
      model: new UntypedFormControl(
        model, [Validators.required]),
      modelYear: new UntypedFormControl(
        modelYear, [Validators.required]),
      type: new UntypedFormControl(
        type, [UtilityRix.dropdownRequired as ValidatorFn]),
      color: new UntypedFormControl(
        color, [Validators.required]),
      armoured: new UntypedFormControl(
        armoured, [Validators.required]),
    });

  }

  cancel(): void {
    this.router.navigate(['/vehicals/pool/all/']);
  }

  submit(): void {
    if (!this.form.valid) {
      this.utilityService.scrollToFirstInvalidControl(this.el, '.page-wrapper');
      return;
    }

    const formValue = this.form.value as VehicalModel;
    formValue.id = this.id;
    const primaryAction = this.editMode ? 'Update' : 'Create';
    const successAction = this.editMode ? 'Updated' : 'Created';
    const primaryMsg = 'Do you want to ' + primaryAction + ' vehical?';

    const dialog: DialogRef = this.dialogService
      .open(this.alertService.getConfirmDialougeConfig(
        'Confirm ' + primaryAction, primaryMsg, primaryAction));

    dialog.result.subscribe((result: any) => {
      if (result.text === primaryAction) {
        this.vehicalService.addUpdate(formValue)
          .subscribe(
            (response: ResponseModel<string>) => {

              if (response.hasError) {
                this.alertService.setErrorAlert(response.msg);
                return;
              }

              this.alertService.setSuccessAlert(
                'Vehical is '
                + successAction
                + ' successfully');

              this.utilityService.redirectToUrl('/vehicals/pool/all');

            }
          );
      }
    });
  }

}
